---
- hosts: all
  tasks:
    - name: install basic packages
      sudo: yes
      apt: pkg={{ item }} state=latest
      tags: [packages]
      with_items:
        - python3
        - python3-dev
        - python3.4-venv
        - mysql-server
        - libmysql++-dev
        - libmysqlclient-dev
        - git
        - emacs24-nox
